__mod_name__ = "Bans"

__help__ = (
    "Some people need to be publicly banned; spammers, annoyances, or just trolls.\n\n"
    "This module allows you to do that easily, by exposing some common actions, so everyone will see!\n\n"
    "**User commands::**\n"
    "- /kickme: Users that use this, kick themselves.\n\n"
    "Admin commands:\n"
    "- /ban: Ban a user.\n"
    "- /dban: Ban a user by reply, and delete their message.\n"
    "- /sban: Silently ban a user, and delete your message.\n"
    "- /tban: Temporarily ban a user.\n"
    "- /unban: Unban a user.\n"
    "- /mute: Mute a user.\n"
    "- /dmute: Mute a user by reply, and delete their message.\n"
    "- /smute: Silently mute a user, and delete your message.\n"
    "- /tmute: Temporarily mute a user.\n"
    "- /unmute: Unmute a user.\n"
    "- /kick: Kick a user.\n"
    "- /dkick: Kick a user by reply, and delete their message.\n"
    "- /skick: Silently kick a user, and delete your message\n\n"
    "**Examples:**\n"
    "- Mute a user for two hours.\n"
    "-> `/tmute @username 2h`"
)